/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/projects.$projectId.settings'
import { Route as AuthenticatedProjectsProjectIdPlansRouteImport } from './routes/_authenticated/projects.$projectId.plans'
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects.$projectId.members'
import { Route as AuthenticatedProjectsProjectIdEndpointsRouteImport } from './routes/_authenticated/projects.$projectId.endpoints'
import { Route as AuthenticatedProjectsProjectIdDocumentsRouteImport } from './routes/_authenticated/projects.$projectId.documents'
import { Route as AuthenticatedProjectsProjectIdCablesRouteImport } from './routes/_authenticated/projects.$projectId.cables'
import { Route as AuthenticatedProjectsProjectIdCableTypesRouteImport } from './routes/_authenticated/projects.$projectId.cable-types'
import { Route as AuthenticatedOrganizationsOrgIdSettingsRouteImport } from './routes/_authenticated/organizations.$orgId.settings'
import { Route as AuthenticatedProjectsProjectIdPlansPlanIdRouteImport } from './routes/_authenticated/projects.$projectId.plans.$planId'
import { Route as AuthenticatedProjectsProjectIdCablesCableIdRouteImport } from './routes/_authenticated/projects.$projectId.cables.$cableId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsRoute =
  AuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPlansRoute =
  AuthenticatedProjectsProjectIdPlansRouteImport.update({
    id: '/projects/$projectId/plans',
    path: '/projects/$projectId/plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/projects/$projectId/members',
    path: '/projects/$projectId/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEndpointsRoute =
  AuthenticatedProjectsProjectIdEndpointsRouteImport.update({
    id: '/projects/$projectId/endpoints',
    path: '/projects/$projectId/endpoints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocumentsRoute =
  AuthenticatedProjectsProjectIdDocumentsRouteImport.update({
    id: '/projects/$projectId/documents',
    path: '/projects/$projectId/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdCablesRoute =
  AuthenticatedProjectsProjectIdCablesRouteImport.update({
    id: '/projects/$projectId/cables',
    path: '/projects/$projectId/cables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdCableTypesRoute =
  AuthenticatedProjectsProjectIdCableTypesRouteImport.update({
    id: '/projects/$projectId/cable-types',
    path: '/projects/$projectId/cable-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdSettingsRoute =
  AuthenticatedOrganizationsOrgIdSettingsRouteImport.update({
    id: '/organizations/$orgId/settings',
    path: '/organizations/$orgId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPlansPlanIdRoute =
  AuthenticatedProjectsProjectIdPlansPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => AuthenticatedProjectsProjectIdPlansRoute,
  } as any)
const AuthenticatedProjectsProjectIdCablesCableIdRoute =
  AuthenticatedProjectsProjectIdCablesCableIdRouteImport.update({
    id: '/$cableId',
    path: '/$cableId',
    getParentRoute: () => AuthenticatedProjectsProjectIdCablesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organizations/$orgId/settings': typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  '/projects/$projectId/cable-types': typeof AuthenticatedProjectsProjectIdCableTypesRoute
  '/projects/$projectId/cables': typeof AuthenticatedProjectsProjectIdCablesRouteWithChildren
  '/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/projects/$projectId/endpoints': typeof AuthenticatedProjectsProjectIdEndpointsRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/plans': typeof AuthenticatedProjectsProjectIdPlansRouteWithChildren
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/cables/$cableId': typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
  '/projects/$projectId/plans/$planId': typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organizations/$orgId/settings': typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  '/projects/$projectId/cable-types': typeof AuthenticatedProjectsProjectIdCableTypesRoute
  '/projects/$projectId/cables': typeof AuthenticatedProjectsProjectIdCablesRouteWithChildren
  '/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/projects/$projectId/endpoints': typeof AuthenticatedProjectsProjectIdEndpointsRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/plans': typeof AuthenticatedProjectsProjectIdPlansRouteWithChildren
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/cables/$cableId': typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
  '/projects/$projectId/plans/$planId': typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/organizations/$orgId/settings': typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  '/_authenticated/projects/$projectId/cable-types': typeof AuthenticatedProjectsProjectIdCableTypesRoute
  '/_authenticated/projects/$projectId/cables': typeof AuthenticatedProjectsProjectIdCablesRouteWithChildren
  '/_authenticated/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/_authenticated/projects/$projectId/endpoints': typeof AuthenticatedProjectsProjectIdEndpointsRoute
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/_authenticated/projects/$projectId/plans': typeof AuthenticatedProjectsProjectIdPlansRouteWithChildren
  '/_authenticated/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/cables/$cableId': typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
  '/_authenticated/projects/$projectId/plans/$planId': typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/audit'
    | '/dashboard'
    | '/organizations/$orgId/settings'
    | '/projects/$projectId/cable-types'
    | '/projects/$projectId/cables'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/endpoints'
    | '/projects/$projectId/members'
    | '/projects/$projectId/plans'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/cables/$cableId'
    | '/projects/$projectId/plans/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/audit'
    | '/dashboard'
    | '/organizations/$orgId/settings'
    | '/projects/$projectId/cable-types'
    | '/projects/$projectId/cables'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/endpoints'
    | '/projects/$projectId/members'
    | '/projects/$projectId/plans'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/cables/$cableId'
    | '/projects/$projectId/plans/$planId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/organizations/$orgId/settings'
    | '/_authenticated/projects/$projectId/cable-types'
    | '/_authenticated/projects/$projectId/cables'
    | '/_authenticated/projects/$projectId/documents'
    | '/_authenticated/projects/$projectId/endpoints'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/plans'
    | '/_authenticated/projects/$projectId/settings'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/cables/$cableId'
    | '/_authenticated/projects/$projectId/plans/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/settings': {
      id: '/_authenticated/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/plans': {
      id: '/_authenticated/projects/$projectId/plans'
      path: '/projects/$projectId/plans'
      fullPath: '/projects/$projectId/plans'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members'
      path: '/projects/$projectId/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/endpoints': {
      id: '/_authenticated/projects/$projectId/endpoints'
      path: '/projects/$projectId/endpoints'
      fullPath: '/projects/$projectId/endpoints'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEndpointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/documents': {
      id: '/_authenticated/projects/$projectId/documents'
      path: '/projects/$projectId/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/cables': {
      id: '/_authenticated/projects/$projectId/cables'
      path: '/projects/$projectId/cables'
      fullPath: '/projects/$projectId/cables'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/cable-types': {
      id: '/_authenticated/projects/$projectId/cable-types'
      path: '/projects/$projectId/cable-types'
      fullPath: '/projects/$projectId/cable-types'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCableTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/$orgId/settings': {
      id: '/_authenticated/organizations/$orgId/settings'
      path: '/organizations/$orgId/settings'
      fullPath: '/organizations/$orgId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/plans/$planId': {
      id: '/_authenticated/projects/$projectId/plans/$planId'
      path: '/$planId'
      fullPath: '/projects/$projectId/plans/$planId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPlansPlanIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdPlansRoute
    }
    '/_authenticated/projects/$projectId/cables/$cableId': {
      id: '/_authenticated/projects/$projectId/cables/$cableId'
      path: '/$cableId'
      fullPath: '/projects/$projectId/cables/$cableId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCablesCableIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdCablesRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdCablesRouteChildren {
  AuthenticatedProjectsProjectIdCablesCableIdRoute: typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
}

const AuthenticatedProjectsProjectIdCablesRouteChildren: AuthenticatedProjectsProjectIdCablesRouteChildren =
  {
    AuthenticatedProjectsProjectIdCablesCableIdRoute:
      AuthenticatedProjectsProjectIdCablesCableIdRoute,
  }

const AuthenticatedProjectsProjectIdCablesRouteWithChildren =
  AuthenticatedProjectsProjectIdCablesRoute._addFileChildren(
    AuthenticatedProjectsProjectIdCablesRouteChildren,
  )

interface AuthenticatedProjectsProjectIdPlansRouteChildren {
  AuthenticatedProjectsProjectIdPlansPlanIdRoute: typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
}

const AuthenticatedProjectsProjectIdPlansRouteChildren: AuthenticatedProjectsProjectIdPlansRouteChildren =
  {
    AuthenticatedProjectsProjectIdPlansPlanIdRoute:
      AuthenticatedProjectsProjectIdPlansPlanIdRoute,
  }

const AuthenticatedProjectsProjectIdPlansRouteWithChildren =
  AuthenticatedProjectsProjectIdPlansRoute._addFileChildren(
    AuthenticatedProjectsProjectIdPlansRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrganizationsOrgIdSettingsRoute: typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  AuthenticatedProjectsProjectIdCableTypesRoute: typeof AuthenticatedProjectsProjectIdCableTypesRoute
  AuthenticatedProjectsProjectIdCablesRoute: typeof AuthenticatedProjectsProjectIdCablesRouteWithChildren
  AuthenticatedProjectsProjectIdDocumentsRoute: typeof AuthenticatedProjectsProjectIdDocumentsRoute
  AuthenticatedProjectsProjectIdEndpointsRoute: typeof AuthenticatedProjectsProjectIdEndpointsRoute
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute
  AuthenticatedProjectsProjectIdPlansRoute: typeof AuthenticatedProjectsProjectIdPlansRouteWithChildren
  AuthenticatedProjectsProjectIdSettingsRoute: typeof AuthenticatedProjectsProjectIdSettingsRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationsOrgIdSettingsRoute:
    AuthenticatedOrganizationsOrgIdSettingsRoute,
  AuthenticatedProjectsProjectIdCableTypesRoute:
    AuthenticatedProjectsProjectIdCableTypesRoute,
  AuthenticatedProjectsProjectIdCablesRoute:
    AuthenticatedProjectsProjectIdCablesRouteWithChildren,
  AuthenticatedProjectsProjectIdDocumentsRoute:
    AuthenticatedProjectsProjectIdDocumentsRoute,
  AuthenticatedProjectsProjectIdEndpointsRoute:
    AuthenticatedProjectsProjectIdEndpointsRoute,
  AuthenticatedProjectsProjectIdMembersRoute:
    AuthenticatedProjectsProjectIdMembersRoute,
  AuthenticatedProjectsProjectIdPlansRoute:
    AuthenticatedProjectsProjectIdPlansRouteWithChildren,
  AuthenticatedProjectsProjectIdSettingsRoute:
    AuthenticatedProjectsProjectIdSettingsRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
