/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrgChatRouteImport } from './routes/_authenticated/org-chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdWorkRouteImport } from './routes/_authenticated/projects.$projectId.work'
import { Route as AuthenticatedProjectsProjectIdSpoolsRouteImport } from './routes/_authenticated/projects.$projectId.spools'
import { Route as AuthenticatedProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/projects.$projectId.settings'
import { Route as AuthenticatedProjectsProjectIdProtocolsRouteImport } from './routes/_authenticated/projects.$projectId.protocols'
import { Route as AuthenticatedProjectsProjectIdPlansRouteImport } from './routes/_authenticated/projects.$projectId.plans'
import { Route as AuthenticatedProjectsProjectIdPatchPanelsRouteImport } from './routes/_authenticated/projects.$projectId.patch-panels'
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects.$projectId.members'
import { Route as AuthenticatedProjectsProjectIdLobbyRouteImport } from './routes/_authenticated/projects.$projectId.lobby'
import { Route as AuthenticatedProjectsProjectIdEndpointsRouteImport } from './routes/_authenticated/projects.$projectId.endpoints'
import { Route as AuthenticatedProjectsProjectIdEndpointKindsRouteImport } from './routes/_authenticated/projects.$projectId.endpoint-kinds'
import { Route as AuthenticatedProjectsProjectIdDocumentsRouteImport } from './routes/_authenticated/projects.$projectId.documents'
import { Route as AuthenticatedProjectsProjectIdDefectsRouteImport } from './routes/_authenticated/projects.$projectId.defects'
import { Route as AuthenticatedProjectsProjectIdCompletionRouteImport } from './routes/_authenticated/projects.$projectId.completion'
import { Route as AuthenticatedProjectsProjectIdCablesRouteImport } from './routes/_authenticated/projects.$projectId.cables'
import { Route as AuthenticatedProjectsProjectIdCableTypesRouteImport } from './routes/_authenticated/projects.$projectId.cable-types'
import { Route as AuthenticatedOrganizationsOrgIdSettingsRouteImport } from './routes/_authenticated/organizations.$orgId.settings'
import { Route as AuthenticatedProjectsProjectIdPlansIndexRouteImport } from './routes/_authenticated/projects.$projectId.plans.index'
import { Route as AuthenticatedProjectsProjectIdPatchPanelsIndexRouteImport } from './routes/_authenticated/projects.$projectId.patch-panels.index'
import { Route as AuthenticatedProjectsProjectIdCompletionIndexRouteImport } from './routes/_authenticated/projects.$projectId.completion.index'
import { Route as AuthenticatedProjectsProjectIdCablesIndexRouteImport } from './routes/_authenticated/projects.$projectId.cables.index'
import { Route as AuthenticatedProjectsProjectIdPlansPlanIdRouteImport } from './routes/_authenticated/projects.$projectId.plans.$planId'
import { Route as AuthenticatedProjectsProjectIdPatchPanelsPanelIdRouteImport } from './routes/_authenticated/projects.$projectId.patch-panels.$panelId'
import { Route as AuthenticatedProjectsProjectIdCompletionKanbanRouteImport } from './routes/_authenticated/projects.$projectId.completion.kanban'
import { Route as AuthenticatedProjectsProjectIdCompletionPlanIdRouteImport } from './routes/_authenticated/projects.$projectId.completion.$planId'
import { Route as AuthenticatedProjectsProjectIdCablesCableIdRouteImport } from './routes/_authenticated/projects.$projectId.cables.$cableId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgChatRoute = AuthenticatedOrgChatRouteImport.update({
  id: '/org-chat',
  path: '/org-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWorkRoute =
  AuthenticatedProjectsProjectIdWorkRouteImport.update({
    id: '/projects/$projectId/work',
    path: '/projects/$projectId/work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSpoolsRoute =
  AuthenticatedProjectsProjectIdSpoolsRouteImport.update({
    id: '/projects/$projectId/spools',
    path: '/projects/$projectId/spools',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsRoute =
  AuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdProtocolsRoute =
  AuthenticatedProjectsProjectIdProtocolsRouteImport.update({
    id: '/projects/$projectId/protocols',
    path: '/projects/$projectId/protocols',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPlansRoute =
  AuthenticatedProjectsProjectIdPlansRouteImport.update({
    id: '/projects/$projectId/plans',
    path: '/projects/$projectId/plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPatchPanelsRoute =
  AuthenticatedProjectsProjectIdPatchPanelsRouteImport.update({
    id: '/projects/$projectId/patch-panels',
    path: '/projects/$projectId/patch-panels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/projects/$projectId/members',
    path: '/projects/$projectId/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdLobbyRoute =
  AuthenticatedProjectsProjectIdLobbyRouteImport.update({
    id: '/projects/$projectId/lobby',
    path: '/projects/$projectId/lobby',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEndpointsRoute =
  AuthenticatedProjectsProjectIdEndpointsRouteImport.update({
    id: '/projects/$projectId/endpoints',
    path: '/projects/$projectId/endpoints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEndpointKindsRoute =
  AuthenticatedProjectsProjectIdEndpointKindsRouteImport.update({
    id: '/projects/$projectId/endpoint-kinds',
    path: '/projects/$projectId/endpoint-kinds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocumentsRoute =
  AuthenticatedProjectsProjectIdDocumentsRouteImport.update({
    id: '/projects/$projectId/documents',
    path: '/projects/$projectId/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdDefectsRoute =
  AuthenticatedProjectsProjectIdDefectsRouteImport.update({
    id: '/projects/$projectId/defects',
    path: '/projects/$projectId/defects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdCompletionRoute =
  AuthenticatedProjectsProjectIdCompletionRouteImport.update({
    id: '/projects/$projectId/completion',
    path: '/projects/$projectId/completion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdCablesRoute =
  AuthenticatedProjectsProjectIdCablesRouteImport.update({
    id: '/projects/$projectId/cables',
    path: '/projects/$projectId/cables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdCableTypesRoute =
  AuthenticatedProjectsProjectIdCableTypesRouteImport.update({
    id: '/projects/$projectId/cable-types',
    path: '/projects/$projectId/cable-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdSettingsRoute =
  AuthenticatedOrganizationsOrgIdSettingsRouteImport.update({
    id: '/organizations/$orgId/settings',
    path: '/organizations/$orgId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPlansIndexRoute =
  AuthenticatedProjectsProjectIdPlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdPlansRoute,
  } as any)
const AuthenticatedProjectsProjectIdPatchPanelsIndexRoute =
  AuthenticatedProjectsProjectIdPatchPanelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdPatchPanelsRoute,
  } as any)
const AuthenticatedProjectsProjectIdCompletionIndexRoute =
  AuthenticatedProjectsProjectIdCompletionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdCompletionRoute,
  } as any)
const AuthenticatedProjectsProjectIdCablesIndexRoute =
  AuthenticatedProjectsProjectIdCablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdCablesRoute,
  } as any)
const AuthenticatedProjectsProjectIdPlansPlanIdRoute =
  AuthenticatedProjectsProjectIdPlansPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => AuthenticatedProjectsProjectIdPlansRoute,
  } as any)
const AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute =
  AuthenticatedProjectsProjectIdPatchPanelsPanelIdRouteImport.update({
    id: '/$panelId',
    path: '/$panelId',
    getParentRoute: () => AuthenticatedProjectsProjectIdPatchPanelsRoute,
  } as any)
const AuthenticatedProjectsProjectIdCompletionKanbanRoute =
  AuthenticatedProjectsProjectIdCompletionKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AuthenticatedProjectsProjectIdCompletionRoute,
  } as any)
const AuthenticatedProjectsProjectIdCompletionPlanIdRoute =
  AuthenticatedProjectsProjectIdCompletionPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => AuthenticatedProjectsProjectIdCompletionRoute,
  } as any)
const AuthenticatedProjectsProjectIdCablesCableIdRoute =
  AuthenticatedProjectsProjectIdCablesCableIdRouteImport.update({
    id: '/$cableId',
    path: '/$cableId',
    getParentRoute: () => AuthenticatedProjectsProjectIdCablesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/org-chat': typeof AuthenticatedOrgChatRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/organizations/$orgId/settings': typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  '/projects/$projectId/cable-types': typeof AuthenticatedProjectsProjectIdCableTypesRoute
  '/projects/$projectId/cables': typeof AuthenticatedProjectsProjectIdCablesRouteWithChildren
  '/projects/$projectId/completion': typeof AuthenticatedProjectsProjectIdCompletionRouteWithChildren
  '/projects/$projectId/defects': typeof AuthenticatedProjectsProjectIdDefectsRoute
  '/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/projects/$projectId/endpoint-kinds': typeof AuthenticatedProjectsProjectIdEndpointKindsRoute
  '/projects/$projectId/endpoints': typeof AuthenticatedProjectsProjectIdEndpointsRoute
  '/projects/$projectId/lobby': typeof AuthenticatedProjectsProjectIdLobbyRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/patch-panels': typeof AuthenticatedProjectsProjectIdPatchPanelsRouteWithChildren
  '/projects/$projectId/plans': typeof AuthenticatedProjectsProjectIdPlansRouteWithChildren
  '/projects/$projectId/protocols': typeof AuthenticatedProjectsProjectIdProtocolsRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/spools': typeof AuthenticatedProjectsProjectIdSpoolsRoute
  '/projects/$projectId/work': typeof AuthenticatedProjectsProjectIdWorkRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/cables/$cableId': typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
  '/projects/$projectId/completion/$planId': typeof AuthenticatedProjectsProjectIdCompletionPlanIdRoute
  '/projects/$projectId/completion/kanban': typeof AuthenticatedProjectsProjectIdCompletionKanbanRoute
  '/projects/$projectId/patch-panels/$panelId': typeof AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute
  '/projects/$projectId/plans/$planId': typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
  '/projects/$projectId/cables/': typeof AuthenticatedProjectsProjectIdCablesIndexRoute
  '/projects/$projectId/completion/': typeof AuthenticatedProjectsProjectIdCompletionIndexRoute
  '/projects/$projectId/patch-panels/': typeof AuthenticatedProjectsProjectIdPatchPanelsIndexRoute
  '/projects/$projectId/plans/': typeof AuthenticatedProjectsProjectIdPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/org-chat': typeof AuthenticatedOrgChatRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/organizations/$orgId/settings': typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  '/projects/$projectId/cable-types': typeof AuthenticatedProjectsProjectIdCableTypesRoute
  '/projects/$projectId/defects': typeof AuthenticatedProjectsProjectIdDefectsRoute
  '/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/projects/$projectId/endpoint-kinds': typeof AuthenticatedProjectsProjectIdEndpointKindsRoute
  '/projects/$projectId/endpoints': typeof AuthenticatedProjectsProjectIdEndpointsRoute
  '/projects/$projectId/lobby': typeof AuthenticatedProjectsProjectIdLobbyRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/protocols': typeof AuthenticatedProjectsProjectIdProtocolsRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/spools': typeof AuthenticatedProjectsProjectIdSpoolsRoute
  '/projects/$projectId/work': typeof AuthenticatedProjectsProjectIdWorkRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/cables/$cableId': typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
  '/projects/$projectId/completion/$planId': typeof AuthenticatedProjectsProjectIdCompletionPlanIdRoute
  '/projects/$projectId/completion/kanban': typeof AuthenticatedProjectsProjectIdCompletionKanbanRoute
  '/projects/$projectId/patch-panels/$panelId': typeof AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute
  '/projects/$projectId/plans/$planId': typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
  '/projects/$projectId/cables': typeof AuthenticatedProjectsProjectIdCablesIndexRoute
  '/projects/$projectId/completion': typeof AuthenticatedProjectsProjectIdCompletionIndexRoute
  '/projects/$projectId/patch-panels': typeof AuthenticatedProjectsProjectIdPatchPanelsIndexRoute
  '/projects/$projectId/plans': typeof AuthenticatedProjectsProjectIdPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/org-chat': typeof AuthenticatedOrgChatRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/organizations/$orgId/settings': typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  '/_authenticated/projects/$projectId/cable-types': typeof AuthenticatedProjectsProjectIdCableTypesRoute
  '/_authenticated/projects/$projectId/cables': typeof AuthenticatedProjectsProjectIdCablesRouteWithChildren
  '/_authenticated/projects/$projectId/completion': typeof AuthenticatedProjectsProjectIdCompletionRouteWithChildren
  '/_authenticated/projects/$projectId/defects': typeof AuthenticatedProjectsProjectIdDefectsRoute
  '/_authenticated/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/_authenticated/projects/$projectId/endpoint-kinds': typeof AuthenticatedProjectsProjectIdEndpointKindsRoute
  '/_authenticated/projects/$projectId/endpoints': typeof AuthenticatedProjectsProjectIdEndpointsRoute
  '/_authenticated/projects/$projectId/lobby': typeof AuthenticatedProjectsProjectIdLobbyRoute
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/_authenticated/projects/$projectId/patch-panels': typeof AuthenticatedProjectsProjectIdPatchPanelsRouteWithChildren
  '/_authenticated/projects/$projectId/plans': typeof AuthenticatedProjectsProjectIdPlansRouteWithChildren
  '/_authenticated/projects/$projectId/protocols': typeof AuthenticatedProjectsProjectIdProtocolsRoute
  '/_authenticated/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/_authenticated/projects/$projectId/spools': typeof AuthenticatedProjectsProjectIdSpoolsRoute
  '/_authenticated/projects/$projectId/work': typeof AuthenticatedProjectsProjectIdWorkRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/cables/$cableId': typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
  '/_authenticated/projects/$projectId/completion/$planId': typeof AuthenticatedProjectsProjectIdCompletionPlanIdRoute
  '/_authenticated/projects/$projectId/completion/kanban': typeof AuthenticatedProjectsProjectIdCompletionKanbanRoute
  '/_authenticated/projects/$projectId/patch-panels/$panelId': typeof AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute
  '/_authenticated/projects/$projectId/plans/$planId': typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
  '/_authenticated/projects/$projectId/cables/': typeof AuthenticatedProjectsProjectIdCablesIndexRoute
  '/_authenticated/projects/$projectId/completion/': typeof AuthenticatedProjectsProjectIdCompletionIndexRoute
  '/_authenticated/projects/$projectId/patch-panels/': typeof AuthenticatedProjectsProjectIdPatchPanelsIndexRoute
  '/_authenticated/projects/$projectId/plans/': typeof AuthenticatedProjectsProjectIdPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/audit'
    | '/dashboard'
    | '/org-chat'
    | '/settings'
    | '/organizations/$orgId/settings'
    | '/projects/$projectId/cable-types'
    | '/projects/$projectId/cables'
    | '/projects/$projectId/completion'
    | '/projects/$projectId/defects'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/endpoint-kinds'
    | '/projects/$projectId/endpoints'
    | '/projects/$projectId/lobby'
    | '/projects/$projectId/members'
    | '/projects/$projectId/patch-panels'
    | '/projects/$projectId/plans'
    | '/projects/$projectId/protocols'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/spools'
    | '/projects/$projectId/work'
    | '/projects/$projectId/'
    | '/projects/$projectId/cables/$cableId'
    | '/projects/$projectId/completion/$planId'
    | '/projects/$projectId/completion/kanban'
    | '/projects/$projectId/patch-panels/$panelId'
    | '/projects/$projectId/plans/$planId'
    | '/projects/$projectId/cables/'
    | '/projects/$projectId/completion/'
    | '/projects/$projectId/patch-panels/'
    | '/projects/$projectId/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/audit'
    | '/dashboard'
    | '/org-chat'
    | '/settings'
    | '/organizations/$orgId/settings'
    | '/projects/$projectId/cable-types'
    | '/projects/$projectId/defects'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/endpoint-kinds'
    | '/projects/$projectId/endpoints'
    | '/projects/$projectId/lobby'
    | '/projects/$projectId/members'
    | '/projects/$projectId/protocols'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/spools'
    | '/projects/$projectId/work'
    | '/projects/$projectId'
    | '/projects/$projectId/cables/$cableId'
    | '/projects/$projectId/completion/$planId'
    | '/projects/$projectId/completion/kanban'
    | '/projects/$projectId/patch-panels/$panelId'
    | '/projects/$projectId/plans/$planId'
    | '/projects/$projectId/cables'
    | '/projects/$projectId/completion'
    | '/projects/$projectId/patch-panels'
    | '/projects/$projectId/plans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/org-chat'
    | '/_authenticated/settings'
    | '/_authenticated/organizations/$orgId/settings'
    | '/_authenticated/projects/$projectId/cable-types'
    | '/_authenticated/projects/$projectId/cables'
    | '/_authenticated/projects/$projectId/completion'
    | '/_authenticated/projects/$projectId/defects'
    | '/_authenticated/projects/$projectId/documents'
    | '/_authenticated/projects/$projectId/endpoint-kinds'
    | '/_authenticated/projects/$projectId/endpoints'
    | '/_authenticated/projects/$projectId/lobby'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/patch-panels'
    | '/_authenticated/projects/$projectId/plans'
    | '/_authenticated/projects/$projectId/protocols'
    | '/_authenticated/projects/$projectId/settings'
    | '/_authenticated/projects/$projectId/spools'
    | '/_authenticated/projects/$projectId/work'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/cables/$cableId'
    | '/_authenticated/projects/$projectId/completion/$planId'
    | '/_authenticated/projects/$projectId/completion/kanban'
    | '/_authenticated/projects/$projectId/patch-panels/$panelId'
    | '/_authenticated/projects/$projectId/plans/$planId'
    | '/_authenticated/projects/$projectId/cables/'
    | '/_authenticated/projects/$projectId/completion/'
    | '/_authenticated/projects/$projectId/patch-panels/'
    | '/_authenticated/projects/$projectId/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org-chat': {
      id: '/_authenticated/org-chat'
      path: '/org-chat'
      fullPath: '/org-chat'
      preLoaderRoute: typeof AuthenticatedOrgChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/work': {
      id: '/_authenticated/projects/$projectId/work'
      path: '/projects/$projectId/work'
      fullPath: '/projects/$projectId/work'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/spools': {
      id: '/_authenticated/projects/$projectId/spools'
      path: '/projects/$projectId/spools'
      fullPath: '/projects/$projectId/spools'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSpoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/settings': {
      id: '/_authenticated/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/protocols': {
      id: '/_authenticated/projects/$projectId/protocols'
      path: '/projects/$projectId/protocols'
      fullPath: '/projects/$projectId/protocols'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdProtocolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/plans': {
      id: '/_authenticated/projects/$projectId/plans'
      path: '/projects/$projectId/plans'
      fullPath: '/projects/$projectId/plans'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/patch-panels': {
      id: '/_authenticated/projects/$projectId/patch-panels'
      path: '/projects/$projectId/patch-panels'
      fullPath: '/projects/$projectId/patch-panels'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members'
      path: '/projects/$projectId/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/lobby': {
      id: '/_authenticated/projects/$projectId/lobby'
      path: '/projects/$projectId/lobby'
      fullPath: '/projects/$projectId/lobby'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdLobbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/endpoints': {
      id: '/_authenticated/projects/$projectId/endpoints'
      path: '/projects/$projectId/endpoints'
      fullPath: '/projects/$projectId/endpoints'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEndpointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/endpoint-kinds': {
      id: '/_authenticated/projects/$projectId/endpoint-kinds'
      path: '/projects/$projectId/endpoint-kinds'
      fullPath: '/projects/$projectId/endpoint-kinds'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEndpointKindsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/documents': {
      id: '/_authenticated/projects/$projectId/documents'
      path: '/projects/$projectId/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/defects': {
      id: '/_authenticated/projects/$projectId/defects'
      path: '/projects/$projectId/defects'
      fullPath: '/projects/$projectId/defects'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDefectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/completion': {
      id: '/_authenticated/projects/$projectId/completion'
      path: '/projects/$projectId/completion'
      fullPath: '/projects/$projectId/completion'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCompletionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/cables': {
      id: '/_authenticated/projects/$projectId/cables'
      path: '/projects/$projectId/cables'
      fullPath: '/projects/$projectId/cables'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/cable-types': {
      id: '/_authenticated/projects/$projectId/cable-types'
      path: '/projects/$projectId/cable-types'
      fullPath: '/projects/$projectId/cable-types'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCableTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/$orgId/settings': {
      id: '/_authenticated/organizations/$orgId/settings'
      path: '/organizations/$orgId/settings'
      fullPath: '/organizations/$orgId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/plans/': {
      id: '/_authenticated/projects/$projectId/plans/'
      path: '/'
      fullPath: '/projects/$projectId/plans/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPlansIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdPlansRoute
    }
    '/_authenticated/projects/$projectId/patch-panels/': {
      id: '/_authenticated/projects/$projectId/patch-panels/'
      path: '/'
      fullPath: '/projects/$projectId/patch-panels/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsRoute
    }
    '/_authenticated/projects/$projectId/completion/': {
      id: '/_authenticated/projects/$projectId/completion/'
      path: '/'
      fullPath: '/projects/$projectId/completion/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCompletionIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdCompletionRoute
    }
    '/_authenticated/projects/$projectId/cables/': {
      id: '/_authenticated/projects/$projectId/cables/'
      path: '/'
      fullPath: '/projects/$projectId/cables/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCablesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdCablesRoute
    }
    '/_authenticated/projects/$projectId/plans/$planId': {
      id: '/_authenticated/projects/$projectId/plans/$planId'
      path: '/$planId'
      fullPath: '/projects/$projectId/plans/$planId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPlansPlanIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdPlansRoute
    }
    '/_authenticated/projects/$projectId/patch-panels/$panelId': {
      id: '/_authenticated/projects/$projectId/patch-panels/$panelId'
      path: '/$panelId'
      fullPath: '/projects/$projectId/patch-panels/$panelId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsPanelIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsRoute
    }
    '/_authenticated/projects/$projectId/completion/kanban': {
      id: '/_authenticated/projects/$projectId/completion/kanban'
      path: '/kanban'
      fullPath: '/projects/$projectId/completion/kanban'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCompletionKanbanRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdCompletionRoute
    }
    '/_authenticated/projects/$projectId/completion/$planId': {
      id: '/_authenticated/projects/$projectId/completion/$planId'
      path: '/$planId'
      fullPath: '/projects/$projectId/completion/$planId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCompletionPlanIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdCompletionRoute
    }
    '/_authenticated/projects/$projectId/cables/$cableId': {
      id: '/_authenticated/projects/$projectId/cables/$cableId'
      path: '/$cableId'
      fullPath: '/projects/$projectId/cables/$cableId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCablesCableIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdCablesRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdCablesRouteChildren {
  AuthenticatedProjectsProjectIdCablesCableIdRoute: typeof AuthenticatedProjectsProjectIdCablesCableIdRoute
  AuthenticatedProjectsProjectIdCablesIndexRoute: typeof AuthenticatedProjectsProjectIdCablesIndexRoute
}

const AuthenticatedProjectsProjectIdCablesRouteChildren: AuthenticatedProjectsProjectIdCablesRouteChildren =
  {
    AuthenticatedProjectsProjectIdCablesCableIdRoute:
      AuthenticatedProjectsProjectIdCablesCableIdRoute,
    AuthenticatedProjectsProjectIdCablesIndexRoute:
      AuthenticatedProjectsProjectIdCablesIndexRoute,
  }

const AuthenticatedProjectsProjectIdCablesRouteWithChildren =
  AuthenticatedProjectsProjectIdCablesRoute._addFileChildren(
    AuthenticatedProjectsProjectIdCablesRouteChildren,
  )

interface AuthenticatedProjectsProjectIdCompletionRouteChildren {
  AuthenticatedProjectsProjectIdCompletionPlanIdRoute: typeof AuthenticatedProjectsProjectIdCompletionPlanIdRoute
  AuthenticatedProjectsProjectIdCompletionKanbanRoute: typeof AuthenticatedProjectsProjectIdCompletionKanbanRoute
  AuthenticatedProjectsProjectIdCompletionIndexRoute: typeof AuthenticatedProjectsProjectIdCompletionIndexRoute
}

const AuthenticatedProjectsProjectIdCompletionRouteChildren: AuthenticatedProjectsProjectIdCompletionRouteChildren =
  {
    AuthenticatedProjectsProjectIdCompletionPlanIdRoute:
      AuthenticatedProjectsProjectIdCompletionPlanIdRoute,
    AuthenticatedProjectsProjectIdCompletionKanbanRoute:
      AuthenticatedProjectsProjectIdCompletionKanbanRoute,
    AuthenticatedProjectsProjectIdCompletionIndexRoute:
      AuthenticatedProjectsProjectIdCompletionIndexRoute,
  }

const AuthenticatedProjectsProjectIdCompletionRouteWithChildren =
  AuthenticatedProjectsProjectIdCompletionRoute._addFileChildren(
    AuthenticatedProjectsProjectIdCompletionRouteChildren,
  )

interface AuthenticatedProjectsProjectIdPatchPanelsRouteChildren {
  AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute
  AuthenticatedProjectsProjectIdPatchPanelsIndexRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsIndexRoute
}

const AuthenticatedProjectsProjectIdPatchPanelsRouteChildren: AuthenticatedProjectsProjectIdPatchPanelsRouteChildren =
  {
    AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute:
      AuthenticatedProjectsProjectIdPatchPanelsPanelIdRoute,
    AuthenticatedProjectsProjectIdPatchPanelsIndexRoute:
      AuthenticatedProjectsProjectIdPatchPanelsIndexRoute,
  }

const AuthenticatedProjectsProjectIdPatchPanelsRouteWithChildren =
  AuthenticatedProjectsProjectIdPatchPanelsRoute._addFileChildren(
    AuthenticatedProjectsProjectIdPatchPanelsRouteChildren,
  )

interface AuthenticatedProjectsProjectIdPlansRouteChildren {
  AuthenticatedProjectsProjectIdPlansPlanIdRoute: typeof AuthenticatedProjectsProjectIdPlansPlanIdRoute
  AuthenticatedProjectsProjectIdPlansIndexRoute: typeof AuthenticatedProjectsProjectIdPlansIndexRoute
}

const AuthenticatedProjectsProjectIdPlansRouteChildren: AuthenticatedProjectsProjectIdPlansRouteChildren =
  {
    AuthenticatedProjectsProjectIdPlansPlanIdRoute:
      AuthenticatedProjectsProjectIdPlansPlanIdRoute,
    AuthenticatedProjectsProjectIdPlansIndexRoute:
      AuthenticatedProjectsProjectIdPlansIndexRoute,
  }

const AuthenticatedProjectsProjectIdPlansRouteWithChildren =
  AuthenticatedProjectsProjectIdPlansRoute._addFileChildren(
    AuthenticatedProjectsProjectIdPlansRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrgChatRoute: typeof AuthenticatedOrgChatRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedOrganizationsOrgIdSettingsRoute: typeof AuthenticatedOrganizationsOrgIdSettingsRoute
  AuthenticatedProjectsProjectIdCableTypesRoute: typeof AuthenticatedProjectsProjectIdCableTypesRoute
  AuthenticatedProjectsProjectIdCablesRoute: typeof AuthenticatedProjectsProjectIdCablesRouteWithChildren
  AuthenticatedProjectsProjectIdCompletionRoute: typeof AuthenticatedProjectsProjectIdCompletionRouteWithChildren
  AuthenticatedProjectsProjectIdDefectsRoute: typeof AuthenticatedProjectsProjectIdDefectsRoute
  AuthenticatedProjectsProjectIdDocumentsRoute: typeof AuthenticatedProjectsProjectIdDocumentsRoute
  AuthenticatedProjectsProjectIdEndpointKindsRoute: typeof AuthenticatedProjectsProjectIdEndpointKindsRoute
  AuthenticatedProjectsProjectIdEndpointsRoute: typeof AuthenticatedProjectsProjectIdEndpointsRoute
  AuthenticatedProjectsProjectIdLobbyRoute: typeof AuthenticatedProjectsProjectIdLobbyRoute
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute
  AuthenticatedProjectsProjectIdPatchPanelsRoute: typeof AuthenticatedProjectsProjectIdPatchPanelsRouteWithChildren
  AuthenticatedProjectsProjectIdPlansRoute: typeof AuthenticatedProjectsProjectIdPlansRouteWithChildren
  AuthenticatedProjectsProjectIdProtocolsRoute: typeof AuthenticatedProjectsProjectIdProtocolsRoute
  AuthenticatedProjectsProjectIdSettingsRoute: typeof AuthenticatedProjectsProjectIdSettingsRoute
  AuthenticatedProjectsProjectIdSpoolsRoute: typeof AuthenticatedProjectsProjectIdSpoolsRoute
  AuthenticatedProjectsProjectIdWorkRoute: typeof AuthenticatedProjectsProjectIdWorkRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrgChatRoute: AuthenticatedOrgChatRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedOrganizationsOrgIdSettingsRoute:
    AuthenticatedOrganizationsOrgIdSettingsRoute,
  AuthenticatedProjectsProjectIdCableTypesRoute:
    AuthenticatedProjectsProjectIdCableTypesRoute,
  AuthenticatedProjectsProjectIdCablesRoute:
    AuthenticatedProjectsProjectIdCablesRouteWithChildren,
  AuthenticatedProjectsProjectIdCompletionRoute:
    AuthenticatedProjectsProjectIdCompletionRouteWithChildren,
  AuthenticatedProjectsProjectIdDefectsRoute:
    AuthenticatedProjectsProjectIdDefectsRoute,
  AuthenticatedProjectsProjectIdDocumentsRoute:
    AuthenticatedProjectsProjectIdDocumentsRoute,
  AuthenticatedProjectsProjectIdEndpointKindsRoute:
    AuthenticatedProjectsProjectIdEndpointKindsRoute,
  AuthenticatedProjectsProjectIdEndpointsRoute:
    AuthenticatedProjectsProjectIdEndpointsRoute,
  AuthenticatedProjectsProjectIdLobbyRoute:
    AuthenticatedProjectsProjectIdLobbyRoute,
  AuthenticatedProjectsProjectIdMembersRoute:
    AuthenticatedProjectsProjectIdMembersRoute,
  AuthenticatedProjectsProjectIdPatchPanelsRoute:
    AuthenticatedProjectsProjectIdPatchPanelsRouteWithChildren,
  AuthenticatedProjectsProjectIdPlansRoute:
    AuthenticatedProjectsProjectIdPlansRouteWithChildren,
  AuthenticatedProjectsProjectIdProtocolsRoute:
    AuthenticatedProjectsProjectIdProtocolsRoute,
  AuthenticatedProjectsProjectIdSettingsRoute:
    AuthenticatedProjectsProjectIdSettingsRoute,
  AuthenticatedProjectsProjectIdSpoolsRoute:
    AuthenticatedProjectsProjectIdSpoolsRoute,
  AuthenticatedProjectsProjectIdWorkRoute:
    AuthenticatedProjectsProjectIdWorkRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
